Fix block/multiline issue in Travis config

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -36,9 +36,9 @@ install:
 
 script:
   - if grep --extended-regexp '^[[:space:]]*using[[:space:]]+System\.Linq;' $(ls MoreLinq.Test/*Test.cs); then
-  -     echo "System.Linq import found, failing the build!" >&2
-  -     exit 1
-  - fi
+        echo "System.Linq import found, failing the build!" >&2
+        exit 1
+    fi
   - ./msbuild.sh /v:m /p:Configuration=$CONFIGURATION
   - dotnet exec MoreLinq.Test/bin/$CONFIGURATION/netcoreapp1.0/MoreLinq.Test.dll
   - dotnet exec MoreLinq.Test/bin/$CONFIGURATION/netcoreapp2.0/MoreLinq.Test.dll
